server.port=${PORT:8080}

# HSQLDB Database (файловая, сохраняется между запусками)
spring.datasource.url=jdbc:hsqldb:file:~/task-solver-db;shutdown=true
spring.datasource.driverClassName=org.hsqldb.jdbc.JDBCDriver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.HSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Thymeleaf
spring.thymeleaf.cache=false

# Mail settings (Gmail)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=macarokrugin@gmail.com
spring.mail.password=vldscfaxitfwhsyj   
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.allow8bitmime=true
logging.level.org.springframework.mail=DEBUG
logging.level.com.sun.mail=DEBUG

# Base URL (для ссылок в письмах)
app.base-url=https://questpulse.onrender.com
# app.base-url=http://localhost:8080           # для локального теста